config/routes.rb
EventManagement::Application.routes.draw do
  root :to => "home#index"
  resources :events, :only => [:index] do
    member do
      get 'teams'
      get 'groups'
      get 'results'
      get 'matches'
      get 'rules'
    end
  end
  resources :feedback, :only => [:new,:create]
  resources :photos, :only => [:index]
  match 'photos/:event' => 'photos#photos', :as => 'event_photos'
  get '/events/:id', to: redirect('/events/%{id}/matches')

  resources :sessions, :only => [:new,:create,:destroy]
  resources :password_resets, :only => [:create,:edit,:update]

  namespace :admin do
    resources :events, :except => :show do
      resources :teams, :except => :show
      resources :rules, :except => :show
      resources :matches
      resources :groups, :except => :show
      resources :results, :only => :index
    end
    resources :users, :except => :show
    resources :feedbacks, :only => :index
    resources :photos, :except => :show
  end

  get "admin" => "admin::dashboard#index"
  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'signup' => 'admin::users#new', :as => 'signup'
  get '/admin/events/:id', to: redirect('/admin/events/%{id}/matches')

  match 'admin/events/:event_id/teams/:team_id/add_player' => 'admin/teams#add_player', :as => 'add_player'
  match 'admin/events/:event_id/teams/:team_id/:user_id/remove_player' => 'admin/teams#remove_player', :as => 'remove_player'
  match 'admin/events/:event_id/teams/:team_id/reset_team' => 'admin/teams#reset_team', :as => 'reset_team'
  match 'admin/events/:event_id/matches/reset_matches' => 'admin/matches#reset_matches', :as => 'reset_matches'
  match 'admin/events/:event_id/groups/:group_id/add_team' => 'admin/groups#add_team', :as => 'add_team'
  match 'admin/events/:event_id/groups/:group_id/:team_id/remove_team' => 'admin/groups#remove_team', :as => 'remove_team'
  match 'admin/events/:event_id/groups/:group_id/reset_group' => 'admin/groups#reset_group', :as => 'reset_group'
  match 'admin/photos/:event/photos' => 'admin/photos#event_photos', :as => 'admin_event_photos'
  match 'admin/events/:event_id/results/:team_id/team_result' => 'admin/results#team_result', :as => 'team_result'
  match 'admin/events/:event_id/results/:team_id/reset_result' => 'admin/results#reset_result', :as => 'reset_result'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :title, :description, :venue, :starts_at, :ends_at

  validates :title, :presence => true, :uniqueness => true

  has_many :teams, :dependent => :destroy
  has_many :rules, :dependent => :destroy
  has_many :matches, :dependent => :destroy
  has_many :groups, :dependent => :destroy
  has_many :photos, :dependent => :destroy

  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController
  add_breadcrumb "Home", :admin_path
  add_breadcrumb "Events", :admin_events_path

  def index
    @events = Event.all
  end

  def new
    add_breadcrumb "New"
    @event = Event.new
  end

  def create
    add_breadcrumb "New"
    @event = Event.new(params[:event])
    if @event.save
      flash[:success] = "Event created!"
      redirect_to admin_events_url
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
    add_breadcrumb "#{@event.title.capitalize}"
  end

  def update
    @event = Event.find(params[:id])
    add_breadcrumb "#{@event.title.capitalize}"

    if @event.update_attributes(params[:event])
      flash[:success] = "Event Updated"
      redirect_to admin_events_path(params[:event_id])
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    TeamUser.where(:event_id => @event.id).delete_all
    @event.destroy
    flash[:success] = "Event Deleted"
    redirect_to admin_events_path
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  add_breadcrumb "Home", :root_path
  add_breadcrumb "Events", :events_path

  def index
    @events = Event.all
  end

  def matches
    @events = Event.all
    #@event = @events.collect { |e| e if e.id.eql?(params[:id].to_i)}.reject { |e| e.nil? }.first
    @event = Event.find(params[:id])  #improved performance
    add_breadcrumb "#{@event.title.capitalize}"
    add_breadcrumb "Matches"
    @matches = @event.matches.order("updated_at DESC")

    @match_results = []
    @match_fixtures = []
    @matches.collect { |m| @match_results << m unless m.result.eql?('nil') }
    @matches.collect { |m| @match_fixtures << m if m.result.eql?('nil') }

    @teams_for_results = []
    @teams_for_fixtures = []

    @match_results.each do |match|
      @teams_for_results << Team.where("id IN (?)", [match.t1,match.t2])
    end

    @match_fixtures = @match_fixtures.reverse!
    @match_fixtures.each do |match|
      @teams_for_fixtures << Team.where("id IN (?)", [match.t1,match.t2])
    end
  end

  def teams
    @events = Event.all
    #@event = @events.collect { |e| e if e.id.eql?(params[:id].to_i)}.reject { |e| e.nil? }.first
    @event = Event.find(params[:id])  #improved performance
    add_breadcrumb "#{@event.title.capitalize}"
    add_breadcrumb "Teams"
    @teams = @event.teams.includes(:players)
  end

  def groups
    @events = Event.all
    #@event = @events.collect { |e| e if e.id.eql?(params[:id].to_i)}.reject { |e| e.nil? }.first
    @event = Event.find(params[:id])  #improved performance
    add_breadcrumb "#{@event.title.capitalize}"
    add_breadcrumb "Groups"
    @groups = @event.groups.includes(:teams)
  end

  def results
    @events = Event.all
    #@event = @events.collect { |e| e if e.id.eql?(params[:id].to_i)}.reject { |e| e.nil? }.first
    @event = Event.find(params[:id])  #improved performance
    add_breadcrumb "#{@event.title.capitalize}"
    add_breadcrumb "Results"
    @teams = @event.teams.includes(:result)
  end

  def rules
    @events = Event.all
    #@event = @events.collect { |e| e if e.id.eql?(params[:id].to_i)}.reject { |e| e.nil? }.first
    @event = Event.find(params[:id])  #improved performance
    add_breadcrumb "#{@event.title.capitalize}"
    add_breadcrumb "Rules"
    @rules = @event.rules
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_fields.html.erb
<p>
  <%= f.label :title %>
  <%= f.text_field :title, :placeholder => "e.g Cricket" %>
</p>
<p>
  <%= f.label :description %>
  <%= f.text_field :description, :placeholder => "e.g Google Gully Cricket" %>
</p>
<p>
  <%= f.label :venue %>
  <%= f.text_field :venue %>
</p>
<p>
  <%= f.label :starts_at %>
  <%= f.datetime_select :starts_at, :ampm => true, :minute_step => 15 %>
</p>
<p>
  <%= f.label :ends_at %>
  <%= f.datetime_select :ends_at, :ampm => true, :minute_step => 15 %>
</p>

app/views/admin/events/edit.html.erb
<div class="msg msg-error">
  <% @event.errors.full_messages.each do |error| %>
    <p><strong><%= error %></strong></p>
  <% end %>
</div>
<div class="content">
<!-- Box -->
  <div class="box">
    <div class="box-head">
      <h2>Edit an Event</h2>
    </div>
    <%= form_for [:admin, @event] do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit  :class => "add-button" %>
      <div class="cl">&nbsp;</div>
    <% end %>
  </div>
<!-- End Box -->
</div>
<p><%= link_to 'back',admin_events_path %></p>

app/views/admin/events/index.html.erb
<div id="content">
  <!-- Box -->
  <div class="box">
    <!-- Box Head -->
    <div class="box-head">
      <h2 class="left">Events</h2>
    </div>
    <!-- End Box Head --> 
    <% if @events.any? %>
      <!-- Table -->
      <div class="table">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <th>Sr No</th>
            <th>Title</th>
            <th>Date created at</th>
            <th>Added by</th>
            <th width="110" class="ac">Content Control</th>
          </tr>
          <% @events.each_with_index do |event,index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= link_to "#{event.title.titleize}", admin_event_matches_path(event.slug) %></td>
            <td><%= event.created_at.strftime("%d-%b-%Y") %></td>
            <td>Administrator</td>
            <td>
              <%= link_to 'Edit', edit_admin_event_path(event), :class => "ico edit" %>
              <%= link_to 'Destroy', admin_event_path(event), :class => "ico del", :method => :delete, :confirm => " Are you sure, you want to delete this event?" %>
            </td>
          <% end %>
        </table>
      </div>
      <!-- Table -->
    <% else %>
     <p>Sorry! There is no events created yet.</p>
    <% end %>
  </div>
  <!-- End Box -->
   <p><%= link_to 'back',admin_path %></p>
</div>

<!-- Sidebar -->
  <div id="sidebar">
    <!-- Box -->
    <div class="box">
      <div class="box-head">
        <h2>Management</h2>
      </div>
      <div class="box-content">
        <%= link_to content_tag(:span, "Create an Event"), new_admin_event_path, :class => "add-button", :method => "get" %>
        <div class="cl">&nbsp;</div>
      </div>
    </div>
    <!-- End Box -->
  </div>
<!-- End Sidebar -->

app/views/admin/events/new.html.erb
<div class="msg msg-error">
  <% @event.errors.full_messages.each do |error| %>
    <p><strong><%= error %></strong></p>
  <% end %>
</div>
<div class="content">
<!-- Box -->
  <div class="box">
    <div class="box-head">
      <h2>Create an Event</h2>
    </div>
    <%= form_for [:admin, @event] do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit :class => "add-button" %>
      <div class="cl">&nbsp;</div>
    <% end %>
  </div>
<!-- End Box -->
</div>
<p><%= link_to 'back',admin_events_path %></p>