config/routes.rb
EventManagement::Application.routes.draw do
  root :to => "home#index"
  resources :events, :only => [:index] do
    member do
      get 'teams'
      get 'groups'
      get 'results'
      get 'matches'
      get 'rules'
    end
  end
  resources :feedback, :only => [:new,:create]
  resources :photos, :only => [:index]
  match 'photos/:event' => 'photos#photos', :as => 'event_photos'
  get '/events/:id', to: redirect('/events/%{id}/matches')

  resources :sessions, :only => [:new,:create,:destroy]
  resources :password_resets, :only => [:create,:edit,:update]

  namespace :admin do
    resources :events, :except => :show do
      resources :teams, :except => :show
      resources :rules, :except => :show
      resources :matches
      resources :groups, :except => :show
      resources :results, :only => :index
    end
    resources :users, :except => :show
    resources :feedbacks, :only => :index
    resources :photos, :except => :show
  end

  get "admin" => "admin::dashboard#index"
  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'signup' => 'admin::users#new', :as => 'signup'
  get '/admin/events/:id', to: redirect('/admin/events/%{id}/matches')

  match 'admin/events/:event_id/teams/:team_id/add_player' => 'admin/teams#add_player', :as => 'add_player'
  match 'admin/events/:event_id/teams/:team_id/:user_id/remove_player' => 'admin/teams#remove_player', :as => 'remove_player'
  match 'admin/events/:event_id/teams/:team_id/reset_team' => 'admin/teams#reset_team', :as => 'reset_team'
  match 'admin/events/:event_id/matches/reset_matches' => 'admin/matches#reset_matches', :as => 'reset_matches'
  match 'admin/events/:event_id/groups/:group_id/add_team' => 'admin/groups#add_team', :as => 'add_team'
  match 'admin/events/:event_id/groups/:group_id/:team_id/remove_team' => 'admin/groups#remove_team', :as => 'remove_team'
  match 'admin/events/:event_id/groups/:group_id/reset_group' => 'admin/groups#reset_group', :as => 'reset_group'
  match 'admin/photos/:event/photos' => 'admin/photos#event_photos', :as => 'admin_event_photos'
  match 'admin/events/:event_id/results/:team_id/team_result' => 'admin/results#team_result', :as => 'team_result'
  match 'admin/events/:event_id/results/:team_id/reset_result' => 'admin/results#reset_result', :as => 'reset_result'

end

app/models/match.rb
class Match < ActiveRecord::Base
  attr_accessible :title, :description, :t1, :t1_desc, :t2, :t2_desc, :result, :event_id

  validates :title, :t1, :t2,:event_id,:presence => true
  belongs_to :event

  validate :cannot_add_same_team

  def cannot_add_same_team
    errors[:base] << "You cannot add identical teams." if self.t1 == self.t2
  end

  scope :result_not_nil, where("result != ?","nil")
end

app/controllers/admin/matches_controller.rb
class Admin::MatchesController < AdminController
  add_breadcrumb "Home", :admin_path
  add_breadcrumb "Events", :admin_events_path

  def index
    @event = Event.find(params[:event_id])
    add_breadcrumb "#{@event.title.capitalize}"
    add_breadcrumb "Matches", :admin_event_matches_path
    @matches = @event.matches.order('updated_at desc')
    @teams = []
    @matches.each do |match|
      @teams << Team.where("id IN (?)", [match.t1,match.t2])
    end
  end

  def new
    @event = Event.find(params[:event_id])
    add_breadcrumb "#{@event.title.capitalize}"
    add_breadcrumb "Matches", :admin_event_matches_path
    add_breadcrumb "New"
    @teams = @event.teams
    if( @teams.size >= 2 )
      @match = @event.matches.new
    else
      flash[:error] = "Create atleast Two Teams First to set Match"
      redirect_to new_admin_event_team_path(params[:event_id])
    end
  end

  def create
    @event = Event.find(params[:event_id])
    add_breadcrumb "#{@event.title.capitalize}"
    add_breadcrumb "Matches", :admin_event_matches_path
    add_breadcrumb "New"
    @teams = @event.teams
    @match = @event.matches.new(params[:match])

    if @match.save
      flash[:success] = "Match created!"
      redirect_to admin_event_matches_path
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:event_id])
    @teams = @event.teams
    @match = Match.find(params[:id])
    add_breadcrumb "#{@event.title.capitalize}"
    add_breadcrumb "Matches", :admin_event_matches_path
    add_breadcrumb "#{@match.title.capitalize}"
  end

  def update
    @event = Event.find(params[:event_id])
    @teams = @event.teams
    @match = Match.find(params[:id])
    add_breadcrumb "#{@event.title.capitalize}"
    add_breadcrumb "Matches", :admin_event_matches_path
    add_breadcrumb "#{@match.title.capitalize}"

    if @match.update_attributes(params[:match])
      flash[:success] = "Match updated!"
      redirect_to admin_event_matches_path(params[:event_id])
    else
      render 'edit'
    end
  end

  def destroy
    @match = Match.find(params[:id])
    @match.destroy
    flash[:success] = "Match Deleted"
    redirect_to admin_event_matches_path
  end

  def show
    @event = Event.find(params[:event_id])
    @match = Match.find(params[:id])
    @teams = Team.where("ID IN (?)", [@match.t1,@match.t2])
    add_breadcrumb "#{@event.title.capitalize}"
    add_breadcrumb "Matches", :admin_event_matches_path
    add_breadcrumb "#{@match.title.capitalize}"
  end

  def reset_matches
    @event = Event.find(params[:event_id])
    begin
      @event.matches.clear
      flash[:success] = "Matches Reset!"
      redirect_to admin_event_matches_path
    rescue
      flash[:error] = "Matches reset failed!"
      redirect_to admin_event_matches_path
    end
  end

end

app/helpers/admin/matches_helper.rb
module Admin::MatchesHelper
end

app/views/admin/matches/_fields.html.erb
<p>
  <%= f.label :title %>
  <%= f.text_field :title, :placeholder => "e.g match- 1" %>
</p>

<p>
  <%= f.label :description %>
  <%= f.cktext_area :description, :ckeditor => {:uiColor => "#E0E0E0"} %>
</p>

<p>
  <%= f.label :first_team %>
  <%= f.select :t1, options_from_collection_for_select(@teams, :id, :title, @match.t1), :prompt=> "--select first team--" %>
</p>

<p>
  <%= f.label :second_team %>
  <%= f.select :t2, options_from_collection_for_select(@teams, :id, :title, @match.t2),:prompt=> "--select second team --" %>

</p>

<p>
  <%= f.label :result_who_won? %>
  <%= f.text_field :result, :value => 'nil' %>
</p>

app/views/admin/matches/edit.html.erb
<div class="shell"><%= render 'admin/shared/tabs' %></div>

<div class="msg msg-error">
  <% @match.errors.full_messages.each do |error| %>
    <p><strong><%= error %></strong></p>
  <% end %>
</div>
<div class="content">
<!-- Box -->
  <div class="box">
    <div class="box-head">
      <h2>Edit <%= @match.title %>
      </h2>
    </div>
    <%= form_for [:admin,:event, @match],:url => admin_event_match_path(params[:event_id],@match) do |f| %>
      <p>
        <%= f.label :title %>
        <%= f.text_field :title, :placeholder => "e.g match- 1" %>
      </p>

      <p>
        <%= f.label :description %>
        <%= f.cktext_area :description, :ckeditor => {:uiColor => "#E0E0E0"} %>
      </p>

      <p>
        <%= f.label :first_team %>
        <%= f.select :t1, options_from_collection_for_select(@teams, :id, :title, @match.t1), :prompt=> "--select first team--" %>
      </p>

      <p>
        <%= f.label :second_team %>
        <%= f.select :t2, options_from_collection_for_select(@teams, :id, :title, @match.t2),:prompt=> "--select second team --" %>
      </p>

      <p>
        <%= f.label :result_who_won? %>
        <%= f.text_field :result %>
      </p>

      <%= f.submit  :class => "add-button" %>
      <div class="cl">&nbsp;</div>
    <% end %>
  </div>
<!-- End Box -->
</div>
<p><%= link_to 'back',admin_event_matches_path %></p>

app/views/admin/matches/index.html.erb
<div class="shell"><%= render 'admin/shared/tabs' %></div>

<div id="content">
  <!-- Box -->
  <div class="box">
    <!-- Box Head -->
    <div class="box-head">
      <h2 class="left">Matches</h2>
    </div>
    <!-- End Box Head --> 
    <% if @matches.any? %>
      <!-- Table -->
      <div class="table">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <th>Sr No</th>
            <th></th>
            <th>Date</th>
            <th>Teams</th>
            <th>Match</th>
            <th width="110" class="ac">Content Control</th>
          </tr>
          <% @matches.each_with_index do |match, index| %>
            <tr>
              <td><%= index + 1 %></td>
              <td style="width:27px"><div class="<%= "played" if match.result != "nil" %>"></div></td>
              <td><%= raw match.description.truncate(30) %></td>
              <td><%= @teams[index][0].title unless @teams[index][0].nil? %> <b>v/s</b> <%= @teams[index][1].title unless @teams[index][1].nil? %></td>
              <td><%= link_to "#{match.title}", admin_event_match_path(params[:event_id],match.id) %></td>
              <td><%= link_to 'edit', edit_admin_event_match_path(params[:event_id],match.id), :class => "ico edit" %>
                  <%= link_to 'destroy', admin_event_match_path(params[:event_id],match.id), :class => "ico del", :method => :delete, :confirm => "Are you sure?" %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
      <!-- Table -->
    <% else %>
     <p>Sorry! There is no Matches.</p>
    <% end %>
  </div>
  <!-- End Box -->
   <p><%= link_to 'back',admin_events_path %></p>
</div>

<!-- Sidebar -->
  <div id="sidebar">
    <!-- Box -->
    <div class="box">
      <div class="box-head">
        <h2>Management</h2>
      </div>
      <div class="box-content">
        <%= link_to content_tag(:span, "Create a Match"), new_admin_event_match_path(params[:event_id]), :class => "add-button", :method => "get" %>
        <div class="cl">&nbsp;</div>
        <% if @matches.any? %>
          <p><%= link_to 'Reset Matches' , reset_matches_path(@event.slug), :confirm => "Are you sure?"  %></p>
        <% end %>
      </div>
    </div>
    <!-- End Box -->
  </div>
<!-- End Sidebar -->

app/views/admin/matches/new.html.erb
<div class="shell"><%= render 'admin/shared/tabs' %></div>

<div class="msg msg-error">
  <% @match.errors.full_messages.each do |error| %>
    <p><strong><%= error %></strong></p>
  <% end %>
</div>
<div class="content">
<!-- Box -->
  <div class="box">
    <div class="box-head">
      <h2>Create a Match</h2>
    </div>
    <%= form_for [:admin,:event, @match] do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit  :class => "add-button" %>
      <div class="cl">&nbsp;</div>
    <% end %>
  </div>
<!-- End Box -->
</div>
<p><%= link_to 'back',admin_event_matches_path %></p>

app/views/admin/matches/show.html.erb
<div class="shell"><%= render 'admin/shared/tabs' %></div>

<div class="content">
  <div class="box">
      <div class="box-head">
        <h2><%= @match.title %>
            <strong>&nbsp;<%= @teams[0].title unless @teams[0].nil? %> <b>v/s</b> <%= @teams[1].title unless @teams[1].nil? %></strong>
            <%= link_to 'edit', edit_admin_event_match_path(params[:event_id],@match.id), :class => "ico edit" %>
            <%= link_to 'destroy', admin_event_match_path(params[:event_id],@match.id), :class => "ico del", :method => :delete, :confirm => "Are you sure?" %>
        </h2>
      </div>
      <div class="box-content">
        <%= raw @match.description %>
        <% if @match.result.nil? || @match.result == 'nil' %>
          <p>No match played!</p>
        <% else %>
          <p>Match Result : <%= @match.result %></p>
        <% end %>
      </div>
  </div>
</div>
<p><%= link_to 'back', admin_event_matches_path(params[:event_id]) %></p>