config/routes.rb
EventManagement::Application.routes.draw do
  root :to => "home#index"
  resources :events, :only => [:index] do
    member do
      get 'teams'
      get 'groups'
      get 'results'
      get 'matches'
      get 'rules'
    end
  end
  resources :feedback, :only => [:new,:create]
  resources :photos, :only => [:index]
  match 'photos/:event' => 'photos#photos', :as => 'event_photos'
  get '/events/:id', to: redirect('/events/%{id}/matches')

  resources :sessions, :only => [:new,:create,:destroy]
  resources :password_resets, :only => [:create,:edit,:update]

  namespace :admin do
    resources :events, :except => :show do
      resources :teams, :except => :show
      resources :rules, :except => :show
      resources :matches
      resources :groups, :except => :show
      resources :results, :only => :index
    end
    resources :users, :except => :show
    resources :feedbacks, :only => :index
    resources :photos, :except => :show
  end

  get "admin" => "admin::dashboard#index"
  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'signup' => 'admin::users#new', :as => 'signup'
  get '/admin/events/:id', to: redirect('/admin/events/%{id}/matches')

  match 'admin/events/:event_id/teams/:team_id/add_player' => 'admin/teams#add_player', :as => 'add_player'
  match 'admin/events/:event_id/teams/:team_id/:user_id/remove_player' => 'admin/teams#remove_player', :as => 'remove_player'
  match 'admin/events/:event_id/teams/:team_id/reset_team' => 'admin/teams#reset_team', :as => 'reset_team'
  match 'admin/events/:event_id/matches/reset_matches' => 'admin/matches#reset_matches', :as => 'reset_matches'
  match 'admin/events/:event_id/groups/:group_id/add_team' => 'admin/groups#add_team', :as => 'add_team'
  match 'admin/events/:event_id/groups/:group_id/:team_id/remove_team' => 'admin/groups#remove_team', :as => 'remove_team'
  match 'admin/events/:event_id/groups/:group_id/reset_group' => 'admin/groups#reset_group', :as => 'reset_group'
  match 'admin/photos/:event/photos' => 'admin/photos#event_photos', :as => 'admin_event_photos'
  match 'admin/events/:event_id/results/:team_id/team_result' => 'admin/results#team_result', :as => 'team_result'
  match 'admin/events/:event_id/results/:team_id/reset_result' => 'admin/results#reset_result', :as => 'reset_result'

end

app/views/shared/_admin_login.html.erb
<% if logged_in? %>
  <div id="login_bar">
    <div class="name">
      <div class ="logout"><%= link_to 'Logout', logout_path %></div>
      <div class="link"><%= link_to "Admin Panel", admin_path %></div>
      Admin Mode: <strong><%= current_user.name %></strong>.
        You are viewing the LIVE website.
    </div>
  </div>
<% end %>

app/views/shared/_feedback_form.html.erb
<div id="dialog-form" title="Feedback Form">
  <p class="validateTips">* indicates required fields.</p>

  <%= form_for @feedback, :url => feedback_index_path, :remote => true do |f| %>
    <table>
      <tr>
        <td><%= f.label :Name %></td>
        <td><%= f.text_field :name %></td>
      </tr>

      <tr>
        <td><%= f.label :Email, :class => "required" %></td>
        <td><%= f.text_field :email %></td>
      </tr>

      <tr>
        <td><%= f.label :Feedback , :class => "required" %></td>
        <td><%= f.text_area :feedback, :size => "60x4" %></td>
      </tr>
    </table>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer>
  <div class="container clearfix">
    <ul class="list-social pull-right">
      <li><%= link_to "",'https://www.facebook.com/parth.bharadiya', target:"_blank", :class => "icon-1" %></li>
      <li><%= link_to "","https://twitter.com/PjBharadiya", target: "_blank", :class => "icon-3" %></li>
      <li><%= link_to "","https://plus.google.com/+ParthBharadiya", target: "_blank", :class => "icon-4" %></li>
    </ul>
    <div class="privacy pull-left">Event Management &copy; 2013 </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
<div class="container clearfix">
  <div class="row">
    <div class="navbar navbar_">
      <div class="container">
        <h1 class="brand"><%= link_to "Event Management", root_path %></h1>
        <%= link_to "","#",:class => "btn btn-navbar btn-navbar_", :data => {:toggle => "collapse", :target => ".nav-collapse_"} %>
        <div class="nav-collapse nav-collapse_  collapse">
          <ul class="nav sf-menu">
            <li><%= link_to 'Home', root_path %></li>
            <li class="menu"><%= link_to 'Events', events_path %>
            <% if @events.any? %>
              <ul class="submenu">
                <% @events.each do |event| %>
                <li><%= link_to "#{event.title.titleize}", matches_event_path(event.slug) %></li>
                <% end %>
              </ul>
            <% end %>
            </li>
            <li><%= link_to 'Photos', photos_path %></li>
            <li><%= link_to 'Contact', "#" %></li>
            <li><%= link_to 'About us', "#" %></li>
            <li><%= link_to 'Feedback', "#", :id => "create-feedback" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
</header>

<%= render 'shared/feedback_form' %>

<%= javascript_include_tag "submit_feedback" %>

app/views/shared/_tabs.html.erb
<style type="text/css">
#dialog-form {
  font-size: 62.5%;
  display: none;
}
.required:after {
  content:"*";
  color: red;
}
.validateTips {
  color: red;
}
#new_feedback table {
  border: none !important;
}
#new_feedback td {
  border: none !important;
  padding: 2px;
  text-align: left;
}
#feedback_feedback {
  max-width: 430px;
  max-height: 117px;
  min-height: 76px;
  min-width: 190px;
}
#nav {
  margin: 32px;
}
#nav, #nav ul{
  padding: 0;
  list-style-type:none;
  list-style-position:outside;
  position:relative;
  line-height:1.5em;
}
#nav ul {
  margin: 33px 0 0 1px;
}
#nav a:link, #nav a:active, #nav a:visited{
  display:block;
  padding:0px 5px;
  color: #000;
  text-decoration:none;
  background-color: #87CEEB;
  border:1px solid #87CEEB;
  outline: none;
}

#nav a:hover{
  background-color:#fff;
  color: red;
  border-radius: 5px 5px 0px 0px;
}
#nav li{
  float:left;
  position:relative;
}
#nav ul {
  position:absolute;
  width:12em;
  top: -0.7em;
  display:none;
}
#nav li ul a{
  width:12em;
  float:left;
}
#nav ul ul{
  top:auto;
  }

#nav li ul ul {
  left:12em;
  margin:0px 0 0 10px;
}

#nav li:hover ul ul, #nav li:hover ul ul ul, #nav li:hover ul ul ul ul{
  display:none;
}
#nav li:hover ul, #nav li li:hover ul, #nav li li li:hover ul, #nav li li li li:hover ul{
  display:block;
}

</style>
<header>
  <ul id="nav">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Events', events_path %>
      <ul>
        <% @events.each do |event| %>
          <li><%= link_to "#{event.title.titleize}", event_path(event.id) %></li>
        <% end %>
      </ul>
    </li>
    <li><%= link_to 'Photos', photos_path %></li>
    <li><%= link_to 'Contact us', "#" %></li>
    <li><%= link_to 'About us', "#" %></li>
    <li>
      <span id="create-feedback">
        <%= link_to 'Feedback', "#" %>
      </span>
    </li>
  </ul>
</header>

<p id="alert_success" class="alert_success">Thank you for your valuable Feedback!</p>

<div id="dialog-form" title="Feedback Form">
  <p class="validateTips">* indicates required fields.</p>

  <%= form_for @feedback, :url => feedback_index_path, :remote => true do |f| %>
    <table>
      <tr>
        <td><%= f.label :Name %></td>
        <td><%= f.text_field :name %></td>
      </tr>

      <tr>
        <td><%= f.label :Email, :class => "required" %></td>
        <td><%= f.text_field :email %></td>
      </tr>

      <tr>
        <td><%= f.label :Feedback , :class => "required" %></td>
        <td><%= f.text_area :feedback, :size => "60x4" %></td>
      </tr>
    </table>
  <% end %>
</div>

<%= javascript_include_tag "submit_feedback" %>