config/routes.rb
EventManagement::Application.routes.draw do
  root :to => "home#index"
  resources :events, :only => [:index] do
    member do
      get 'teams'
      get 'groups'
      get 'results'
      get 'matches'
      get 'rules'
    end
  end
  resources :feedback, :only => [:new,:create]
  resources :photos, :only => [:index]
  match 'photos/:event' => 'photos#photos', :as => 'event_photos'
  get '/events/:id', to: redirect('/events/%{id}/matches')

  resources :sessions, :only => [:new,:create,:destroy]
  resources :password_resets, :only => [:create,:edit,:update]

  namespace :admin do
    resources :events, :except => :show do
      resources :teams, :except => :show
      resources :rules, :except => :show
      resources :matches
      resources :groups, :except => :show
      resources :results, :only => :index
    end
    resources :users, :except => :show
    resources :feedbacks, :only => :index
    resources :photos, :except => :show
  end

  get "admin" => "admin::dashboard#index"
  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'signup' => 'admin::users#new', :as => 'signup'
  get '/admin/events/:id', to: redirect('/admin/events/%{id}/matches')

  match 'admin/events/:event_id/teams/:team_id/add_player' => 'admin/teams#add_player', :as => 'add_player'
  match 'admin/events/:event_id/teams/:team_id/:user_id/remove_player' => 'admin/teams#remove_player', :as => 'remove_player'
  match 'admin/events/:event_id/teams/:team_id/reset_team' => 'admin/teams#reset_team', :as => 'reset_team'
  match 'admin/events/:event_id/matches/reset_matches' => 'admin/matches#reset_matches', :as => 'reset_matches'
  match 'admin/events/:event_id/groups/:group_id/add_team' => 'admin/groups#add_team', :as => 'add_team'
  match 'admin/events/:event_id/groups/:group_id/:team_id/remove_team' => 'admin/groups#remove_team', :as => 'remove_team'
  match 'admin/events/:event_id/groups/:group_id/reset_group' => 'admin/groups#reset_group', :as => 'reset_group'
  match 'admin/photos/:event/photos' => 'admin/photos#event_photos', :as => 'admin_event_photos'
  match 'admin/events/:event_id/results/:team_id/team_result' => 'admin/results#team_result', :as => 'team_result'
  match 'admin/events/:event_id/results/:team_id/reset_result' => 'admin/results#reset_result', :as => 'reset_result'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :title, :description, :venue, :starts_at, :ends_at

  validates :title, :presence => true, :uniqueness => true

  has_many :teams, :dependent => :destroy
  has_many :rules, :dependent => :destroy
  has_many :matches, :dependent => :destroy
  has_many :groups, :dependent => :destroy
  has_many :photos, :dependent => :destroy

  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController
  add_breadcrumb "Home", :admin_path
  add_breadcrumb "Events", :admin_events_path

  def index
    @events = Event.all
  end

  def new
    add_breadcrumb "New"
    @event = Event.new
  end

  def create
    add_breadcrumb "New"
    @event = Event.new(params[:event])
    if @event.save
      flash[:success] = "Event created!"
      redirect_to admin_events_url
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
    add_breadcrumb "#{@event.title.capitalize}"
  end

  def update
    @event = Event.find(params[:id])
    add_breadcrumb "#{@event.title.capitalize}"

    if @event.update_attributes(params[:event])
      flash[:success] = "Event Updated"
      redirect_to admin_events_path(params[:event_id])
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    TeamUser.where(:event_id => @event.id).delete_all
    @event.destroy
    flash[:success] = "Event Deleted"
    redirect_to admin_events_path
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  add_breadcrumb "Home", :root_path
  add_breadcrumb "Events", :events_path

  def index
    @events = Event.all
  end

  def matches
    @events = Event.all
    #@event = @events.collect { |e| e if e.id.eql?(params[:id].to_i)}.reject { |e| e.nil? }.first
    @event = Event.find(params[:id])  #improved performance
    add_breadcrumb "#{@event.title.capitalize}"
    add_breadcrumb "Matches"
    @matches = @event.matches.order("updated_at DESC")

    @match_results = []
    @match_fixtures = []
    @matches.collect { |m| @match_results << m unless m.result.eql?('nil') }
    @matches.collect { |m| @match_fixtures << m if m.result.eql?('nil') }

    @teams_for_results = []
    @teams_for_fixtures = []

    @match_results.each do |match|
      @teams_for_results << Team.where("id IN (?)", [match.t1,match.t2])
    end

    @match_fixtures = @match_fixtures.reverse!
    @match_fixtures.each do |match|
      @teams_for_fixtures << Team.where("id IN (?)", [match.t1,match.t2])
    end
  end

  def teams
    @events = Event.all
    #@event = @events.collect { |e| e if e.id.eql?(params[:id].to_i)}.reject { |e| e.nil? }.first
    @event = Event.find(params[:id])  #improved performance
    add_breadcrumb "#{@event.title.capitalize}"
    add_breadcrumb "Teams"
    @teams = @event.teams.includes(:players)
  end

  def groups
    @events = Event.all
    #@event = @events.collect { |e| e if e.id.eql?(params[:id].to_i)}.reject { |e| e.nil? }.first
    @event = Event.find(params[:id])  #improved performance
    add_breadcrumb "#{@event.title.capitalize}"
    add_breadcrumb "Groups"
    @groups = @event.groups.includes(:teams)
  end

  def results
    @events = Event.all
    #@event = @events.collect { |e| e if e.id.eql?(params[:id].to_i)}.reject { |e| e.nil? }.first
    @event = Event.find(params[:id])  #improved performance
    add_breadcrumb "#{@event.title.capitalize}"
    add_breadcrumb "Results"
    @teams = @event.teams.includes(:result)
  end

  def rules
    @events = Event.all
    #@event = @events.collect { |e| e if e.id.eql?(params[:id].to_i)}.reject { |e| e.nil? }.first
    @event = Event.find(params[:id])  #improved performance
    add_breadcrumb "#{@event.title.capitalize}"
    add_breadcrumb "Rules"
    @rules = @event.rules
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_tabs.html.erb
<div class="row">
  <ul class="tabs">
    <li><%= link_to 'Matches', matches_event_path(@event.slug) %> </li>
    <li><%= link_to 'Teams', teams_event_path(@event.slug) %> </li>
    <li><%= link_to 'Groups', groups_event_path(@event.slug) %> </li>
    <li><%= link_to 'Results', results_event_path(@event.slug) %> </li>
    <li><%= link_to 'Rules', rules_event_path(@event.slug) %></li>
  </ul>
</div>

app/views/events/groups.html.erb
<%= render 'tabs' %>

<h4>Groups</h4>
<% if @groups.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <% @groups.each_with_index do |group,index| %>
          <th><%= group.title %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <tr>
        <% @groups.each_with_index do |group,index| %>
          <td>
            <% if group.teams.any? %>
              <ul>
                <% group.teams.each do |team| %>
                  <li><%= team.title %></li>
                <% end %>
              </ul>
            <% else %>
              No Teams selected!
            <% end %>
          </td>
        <% end %>
      </tr>
    </tbody>
  </table>
<% else %>
  <p>No Group selected!</p>
<% end %>

<p><%= link_to 'back', events_path %></p>

app/views/events/index.html.erb
<h4>Events</h4>

<table class="table table-striped">
  <thead>
    <tr>
      <th style="width:30px">#</th>
      <th>Event</th>
      <th>Description</th>
      <th>Venue</th>
      <th>Time</th>
    </tr>
  </thead>
  <% @events.each_with_index do |event,index| %>
  <tbody>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= link_to "#{event.title.titleize}", matches_event_path(event.slug), :title => "See Event Details" %></td>
      <td><%= event.description %></td>
      <td><%= event.venue %></td>
      <td>
        <b>Date :</b><%= event.starts_at.strftime("%d-%b-%Y") %></br>
        <b>Time :</b><%= event.starts_at.strftime("%I:%M %p") %><b>--</b><%= event.ends_at.strftime("%I:%M %p") %>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>

<p><%= link_to 'back', root_path %></p>

app/views/events/matches.html.erb
<%= render 'tabs' %>

<h4>Matches</h4>
<% if @matches.any? %>
  <div class="row">
  <span id="fixtures"><%= link_to "Fixtures", "#" %></span>
  <span id="results" class="active"><%= link_to "Results", "#" %></span></div>

  <div class="fixtures" style="display: none">
    <% if @match_fixtures.any? %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th >Sr No.</th>
            <th>Date</th>
            <th>Teams</th>
            <th>Match</th>
          </tr>
        </thead>
        <% j = 0 %>
        <% @match_fixtures.each_with_index do |match,index| %>
          <tbody>
            <tr>
              <td><%= index +1 %></td>
              <td><%= raw match.description %></td>
              <td><%= @teams_for_fixtures[j][0].title unless @teams_for_fixtures[j][0].nil? %><b> v/s </b><%= @teams_for_fixtures[j][1].title unless @teams_for_fixtures[j][1].nil? %></td>
              <td><%= match.title %></td>
            </tr>
          </tbody>
          <% j+=1 %>
        <% end %>
      </table>
    <% else %>
      No Fixtures!
    <% end %>
  </div>

  <div class="results">
    <% if @match_results.any? %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th >Sr No.</th>
            <th>Date</th>
            <th>Teams</th>
            <th>Match</th>
            <th>Result &nbsp;<%= link_to 'Point Table', results_event_path(@event.slug) %></th>
          </tr>
        </thead>
        <% i = 0 %>
        <% @match_results.each_with_index do |match,index| %>
          <tbody>
            <tr>
              <td><%= index +1 %></td>
              <td><%= raw match.description %></td>
              <td><%= @teams_for_results[i][0].title unless @teams_for_results[i][0].nil? %><b> v/s </b><%= @teams_for_results[i][1].title unless @teams_for_results[i][1].nil? %></td>
              <td><%= match.title %></td>
              <td><%= match.result %></td>
            </tr>
          </tbody>
          <% i+=1 %>
        <% end %>
      </table>
    <% else %>
      <p>No Results!</p>
    <% end %>
  </div>
<% else %>
  <p>No matches!</p>
<% end %>

<p><%= link_to 'back', events_path %></p>


<script type="text/javascript">
$("#fixtures").click(function () {
  $(".fixtures").slideDown(1000);
  $(".results").slideUp(500);
  $("#fixtures").addClass("active");
  $("#results").removeClass("active");
})

$("#results").click(function () {
  $(".results").slideDown(1000);
  $(".fixtures").slideUp(500);
  $("#results").addClass("active");
  $("#fixtures").removeClass("active");
})
</script>

app/views/events/results.html.erb
<%= render 'tabs' %>

<h4>Results</h4>
<% if @teams.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th >Sr No.</th>
        <th>Team Name</th>
        <th>Played</th>
        <th>Won</th>
        <th>Lost</th>
        <th>Tie</th>
        <th>NR</th>
        <th>Points</th>
        <th>NRR</th>
      </tr>
    </thead>
    <% @teams.each_with_index do |team,index| %>
      <% unless team.result.nil? %>
        <tbody>
          <tr>
            <td><%= index +1 %></td>
            <td style="text-align: left;"><%= team.title %><%= team.description %></td>
            <td><%= team.result.played %></td>
            <td><%= team.result.won %></td>
            <td><%= team.result.lost %></td>
            <td><%= team.result.tie %></td>
            <td><%= team.result.nr %></td>
            <td><%= team.result.points %></td>
            <td><%= team.result.nrr %></td>
          </tr>
        </tbody>
      <% end %>
    <% end %>
  </table>
<% else %>
  <p>No results!</p>
<% end %>

<p><%= link_to 'back', events_path %></p>

app/views/events/rules.html.erb
<%= render 'tabs' %>

<h4>Rules</h4>

<table class="table table-striped">
  <tbody>
    <tr>
      <td style="text-align: left;">
        <% if @rules.any? %>
          <% @rules.each do |rule| %>
            <%= raw rule.description %>
          <% end %>
        <% else %>
          Why should all the games have rules!! Cheers!
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

<p><%= link_to 'back', events_path %></p>

app/views/events/show_teams.html.erb
<style type="text/css">
table {
  border:1px solid;
  border-collapse:collapse;
}
th {
  border:1px solid;
  padding: 5px;
  border-color: #000080;
}
td {
  border:1px solid;
  border-color: #000080;
  width: 136px;
}
</style>
<h1><%= @event.title.titleize %>&nbsp;Teams</h1>
<% if @teams.any? %>
  <table>
    <tr>
      <% @teams.each_with_index do |team,index| %>
        <th>Team&nbsp;<%= team.title %>(<%= team.description %>)</th>
      <% end %>
    </tr>
    <tr>
      <% @teams.each_with_index do |team,index| %>
        <td>
          <ul>
            <% if team.players.any? %>
              <% team.players.each do |player| %>
                <li><%= player.name %></li>
              <% end %>
            <% else %>
              No players selected!
            <% end %>
          </ul>
        </td>
      <% end %>
    </tr>
  </table>
<% else %>
  No Teams selected!
<% end %>

<h2>Rules</h2>
<% if @rules.any? %>
  <% @rules.each_with_index do |rule,index| %>
    <p>
      (<%= index + 1 %>)
      <%= rule.description %>
    </p>
  <% end %>
<% else %>
  <p>Why should all the games have rules!! Cheers!</p>
<% end %>

<%= link_to 'back', results_event_path %>

app/views/events/teams.html.erb
<%= render 'tabs' %>

<h4>Teams</h4>
<% if @teams.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <% @teams.each_with_index do |team,index| %>
          <th><%= team.title %><%= team.description %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <tr>
        <% @teams.each_with_index do |team,index| %>
          <td>
            <% if team.players.any? %>
              <ul>
                <% team.players.each do |player| %>
                  <li><%= player.name %></li>
                <% end %>
              </ul>
            <% else %>
              No players selected!
            <% end %>
          </td>
        <% end %>
      </tr>
    </tbody>
  </table>
<% else %>
  <p>No Teams selected!</p>
<% end %>

<p><%= link_to 'back', events_path %></p>